name: Spider action

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Debug the token
      run: echo "TOKEN is $TOKEN"

    - name: Run the script
      env:
        TOKEN: ${{ secrets.TOKEN }}  # GitHub token stored in the secrets
      run: |
        python main.py $TOKEN
